name: Docker Build and Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get current timestamp
      id: timestamp
      run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.timestamp }}
          ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
